use super::AgentCapability::FileWrite;
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{def, ToolDefinition, TOOL_CATEGORY_EDIT};
use crate::tool_runtime::metadata::{
    ToolPathHint::{PathList, SinglePath},
    ToolRisk::ProjectWrite,
    PROJECT_WRITE, TOOL_PROVIDER_AGENT,
};

// Single-purpose edit primitives superseded by the transactional
// `apply_text_edits` batch. Kept dispatchable for back-compat, but withheld
// from the model surface so it does not compete with the canonical entry.
pub(super) const COMPATIBILITY_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "replace_in_file",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "replace_exact_block",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "insert_before_pattern",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "insert_after_pattern",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "write_project_file",
        ModelVisible,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
];

pub(super) const LINE_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "replace_line_range",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "insert_at_line",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "delete_line_range",
        ModelHidden,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "apply_text_edits",
        ModelVisible,
        TOOL_CATEGORY_EDIT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        PathList,
        false,
        false,
    ),
];
